# Generated by Django 5.1.1 on 2024-09-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=255)),
                ('chief_fio', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
