# Generated by Django 5.1.1 on 2024-09-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=50)),
                ('shortName', models.CharField(max_length=20)),
                ('fullName', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('chiefFIO', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
