# Generated by Django 5.1.1 on 2024-09-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherStationsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='sea_level',
            field=models.IntegerField(default=0),
        ),
    ]
