# Generated by Django 5.1.1 on 2024-09-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherStationsApp', '0002_station_sea_level'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='station',
            table='stations',
        ),
    ]
