# Generated by Django 5.1.1 on 2024-09-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherStationsApp', '0003_alter_station_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='station',
            name='photo',
        ),
        migrations.AddField(
            model_name='station',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='station',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Deleted')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='station',
            name='chief_fio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='station',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
