# Generated by Django 5.1.1 on 2024-09-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherStationsApp', '0006_temperature_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(default=0)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeatherStationsApp.temperature_report')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeatherStationsApp.station')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('station_id', 'report_id'), name='unique_station_report')],
            },
        ),
    ]
