# Generated by Django 5.1.1 on 2024-09-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherStationsApp', '0007_station_report'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='station_report',
            table='stations_reports',
        ),
    ]
