# Generated by Django 5.1.1 on 2024-09-22 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherStationsApp', '0008_alter_station_report_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature_report',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 22, 9, 25, 28, 331762, tzinfo=datetime.timezone.utc)),
        ),
    ]
