# Generated by Django 5.1.1 on 2024-09-24 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherStationsApp', '0009_alter_temperature_report_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature_report',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 24, 10, 20, 51, 111191, tzinfo=datetime.timezone.utc)),
        ),
    ]
