# Generated by Django 5.1.1 on 2024-10-06 15:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherStationsApp', '0010_alter_temperature_report_report_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature_report',
            name='creator_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temperature_report',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 6, 15, 25, 14, 586405, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
