# Generated by Django 5.1.1 on 2024-10-06 16:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deleted')], default='A', max_length=1)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('chief_fio', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('sea_level', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='Temperature_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Deleted', 'Deleted'), ('Formed', 'formed'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Draft', max_length=9)),
                ('report_date', models.DateField(default=datetime.datetime(2024, 10, 6, 16, 17, 59, 925485, tzinfo=datetime.timezone.utc))),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('formation_date', models.DateTimeField(null=True)),
                ('completion_date', models.DateTimeField(null=True)),
                ('creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('moderator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_moderated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Station_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(default=0)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.station')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.temperature_report')),
            ],
            options={
                'db_table': 'stations_reports',
                'constraints': [models.UniqueConstraint(fields=('station_id', 'report_id'), name='unique_station_report')],
            },
        ),
    ]
