# Generated by Django 5.1.1 on 2024-10-23 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature_report',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 23, 11, 8, 59, 823030, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
