# Generated by Django 5.1.1 on 2024-10-06 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_authuser_alter_temperature_report_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature_report',
            name='average_temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temperature_report',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 6, 18, 49, 32, 792429, tzinfo=datetime.timezone.utc)),
        ),
    ]
