# Generated by Django 5.1.1 on 2024-10-07 18:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_temperature_report_average_temperature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature_report',
            name='average_temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='temperature_report',
            name='creator_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temperature_report',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 18, 6, 47, 745167, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
