# Generated by Django 5.1.1 on 2024-10-07 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_temperature_report_average_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature_report',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 19, 3, 5, 550232, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
